#!/bin/bash
#SBATCH --job-name=qwen3-8b-sf-gen
#SBATCH --array=0-65%1
#SBATCH --cpus-per-task=8
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --time=36:00:00
#SBATCH --mem=64GB
#SBATCH --gres=gpu:1
#SBATCH --output=experiments/slurm_logs/qwen3_8b_sf_spanish_generation_%A_%a.log
#SBATCH --error=experiments/slurm_logs/qwen3_8b_sf_spanish_generation_%A_%a.err
#SBATCH --mail-type=END,FAIL,REQUEUE
#SBATCH --mail-user=igutierrez134@ikasle.ehu.eus

set -euo pipefail

CONFIGS=(
  configs/experiments/250_qwen3_8b_no_rag_no_think_extractive_sns1064_sf_dev.json
  configs/experiments/251_qwen3_8b_rag_e5_topk1_no_think_extractive_sns1064_sf_dev.json
  configs/experiments/252_qwen3_8b_rag_e5_topk3_no_think_extractive_sns1064_sf_dev.json
  configs/experiments/253_qwen3_8b_rag_e5_topk5_no_think_extractive_sns1064_sf_dev.json
  configs/experiments/254_qwen3_8b_rag_e5_rerank1_no_think_extractive_sns1064_sf_dev.json
  configs/experiments/255_qwen3_8b_rag_e5_rerank3_no_think_extractive_sns1064_sf_dev.json
  configs/experiments/256_qwen3_8b_rag_e5_rerank5_no_think_extractive_sns1064_sf_dev.json
  configs/experiments/257_qwen3_8b_3shot_no_rag_no_think_extractive_sns1064_sf_dev.json
  configs/experiments/258_qwen3_8b_rag_cross_domain_e5_rerank5_no_think_extractive_sns1064_sf_dev.json
  configs/experiments/259_qwen3_8b_rag_mixed_e5_rerank5_no_think_extractive_sns1064_sf_dev.json
  configs/experiments/260_qwen3_8b_rag_3shot_e5_rerank5_no_think_extractive_sns1064_sf_dev.json
  configs/experiments/261_qwen3_8b_no_rag_think_extractive_sns1064_sf_dev.json
  configs/experiments/262_qwen3_8b_rag_e5_topk1_think_extractive_sns1064_sf_dev.json
  configs/experiments/263_qwen3_8b_rag_e5_topk3_think_extractive_sns1064_sf_dev.json
  configs/experiments/264_qwen3_8b_rag_e5_topk5_think_extractive_sns1064_sf_dev.json
  configs/experiments/265_qwen3_8b_rag_e5_rerank1_think_extractive_sns1064_sf_dev.json
  configs/experiments/266_qwen3_8b_rag_e5_rerank3_think_extractive_sns1064_sf_dev.json
  configs/experiments/267_qwen3_8b_rag_e5_rerank5_think_extractive_sns1064_sf_dev.json
  configs/experiments/268_qwen3_8b_3shot_no_rag_think_extractive_sns1064_sf_dev.json
  configs/experiments/269_qwen3_8b_rag_cross_domain_e5_rerank5_think_extractive_sns1064_sf_dev.json
  configs/experiments/270_qwen3_8b_rag_mixed_e5_rerank5_think_extractive_sns1064_sf_dev.json
  configs/experiments/271_qwen3_8b_rag_3shot_e5_rerank5_think_extractive_sns1064_sf_dev.json
  configs/experiments/272_qwen3_8b_no_rag_no_think_extractive_casimedicos_sf_dev.json
  configs/experiments/273_qwen3_8b_rag_e5_topk1_no_think_extractive_casimedicos_sf_dev.json
  configs/experiments/274_qwen3_8b_rag_e5_topk3_no_think_extractive_casimedicos_sf_dev.json
  configs/experiments/275_qwen3_8b_rag_e5_topk5_no_think_extractive_casimedicos_sf_dev.json
  configs/experiments/276_qwen3_8b_rag_e5_rerank1_no_think_extractive_casimedicos_sf_dev.json
  configs/experiments/277_qwen3_8b_rag_e5_rerank3_no_think_extractive_casimedicos_sf_dev.json
  configs/experiments/278_qwen3_8b_rag_e5_rerank5_no_think_extractive_casimedicos_sf_dev.json
  configs/experiments/279_qwen3_8b_3shot_no_rag_no_think_extractive_casimedicos_sf_dev.json
  configs/experiments/280_qwen3_8b_rag_cross_domain_e5_rerank5_no_think_extractive_casimedicos_sf_dev.json
  configs/experiments/281_qwen3_8b_rag_mixed_e5_rerank5_no_think_extractive_casimedicos_sf_dev.json
  configs/experiments/282_qwen3_8b_rag_3shot_e5_rerank5_no_think_extractive_casimedicos_sf_dev.json
  configs/experiments/283_qwen3_8b_no_rag_think_extractive_casimedicos_sf_dev.json
  configs/experiments/284_qwen3_8b_rag_e5_topk1_think_extractive_casimedicos_sf_dev.json
  configs/experiments/285_qwen3_8b_rag_e5_topk3_think_extractive_casimedicos_sf_dev.json
  configs/experiments/286_qwen3_8b_rag_e5_topk5_think_extractive_casimedicos_sf_dev.json
  configs/experiments/287_qwen3_8b_rag_e5_rerank1_think_extractive_casimedicos_sf_dev.json
  configs/experiments/288_qwen3_8b_rag_e5_rerank3_think_extractive_casimedicos_sf_dev.json
  configs/experiments/289_qwen3_8b_rag_e5_rerank5_think_extractive_casimedicos_sf_dev.json
  configs/experiments/290_qwen3_8b_3shot_no_rag_think_extractive_casimedicos_sf_dev.json
  configs/experiments/291_qwen3_8b_rag_cross_domain_e5_rerank5_think_extractive_casimedicos_sf_dev.json
  configs/experiments/292_qwen3_8b_rag_mixed_e5_rerank5_think_extractive_casimedicos_sf_dev.json
  configs/experiments/293_qwen3_8b_rag_3shot_e5_rerank5_think_extractive_casimedicos_sf_dev.json
  configs/experiments/294_qwen3_8b_no_rag_no_think_extractive_mixed_sf_dev.json
  configs/experiments/295_qwen3_8b_rag_e5_topk1_no_think_extractive_mixed_sf_dev.json
  configs/experiments/296_qwen3_8b_rag_e5_topk3_no_think_extractive_mixed_sf_dev.json
  configs/experiments/297_qwen3_8b_rag_e5_topk5_no_think_extractive_mixed_sf_dev.json
  configs/experiments/298_qwen3_8b_rag_e5_rerank1_no_think_extractive_mixed_sf_dev.json
  configs/experiments/299_qwen3_8b_rag_e5_rerank3_no_think_extractive_mixed_sf_dev.json
  configs/experiments/300_qwen3_8b_rag_e5_rerank5_no_think_extractive_mixed_sf_dev.json
  configs/experiments/301_qwen3_8b_3shot_no_rag_no_think_extractive_mixed_sf_dev.json
  configs/experiments/302_qwen3_8b_rag_sns1064_e5_rerank5_no_think_extractive_mixed_sf_dev.json
  configs/experiments/303_qwen3_8b_rag_casimedicos_e5_rerank5_no_think_extractive_mixed_sf_dev.json
  configs/experiments/304_qwen3_8b_rag_3shot_e5_rerank5_no_think_extractive_mixed_sf_dev.json
  configs/experiments/305_qwen3_8b_no_rag_think_extractive_mixed_sf_dev.json
  configs/experiments/306_qwen3_8b_rag_e5_topk1_think_extractive_mixed_sf_dev.json
  configs/experiments/307_qwen3_8b_rag_e5_topk3_think_extractive_mixed_sf_dev.json
  configs/experiments/308_qwen3_8b_rag_e5_topk5_think_extractive_mixed_sf_dev.json
  configs/experiments/309_qwen3_8b_rag_e5_rerank1_think_extractive_mixed_sf_dev.json
  configs/experiments/310_qwen3_8b_rag_e5_rerank3_think_extractive_mixed_sf_dev.json
  configs/experiments/311_qwen3_8b_rag_e5_rerank5_think_extractive_mixed_sf_dev.json
  configs/experiments/312_qwen3_8b_3shot_no_rag_think_extractive_mixed_sf_dev.json
  configs/experiments/313_qwen3_8b_rag_sns1064_e5_rerank5_think_extractive_mixed_sf_dev.json
  configs/experiments/314_qwen3_8b_rag_casimedicos_e5_rerank5_think_extractive_mixed_sf_dev.json
  configs/experiments/315_qwen3_8b_rag_3shot_e5_rerank5_think_extractive_mixed_sf_dev.json
)

CONFIG="${CONFIGS[$SLURM_ARRAY_TASK_ID]}"

source /home/igutierrez134/envs/med_rag_thesis/bin/activate

export HF_HOME="/home/igutierrez134/.cache/huggingface"
export TRANSFORMERS_CACHE="/home/igutierrez134/.cache/huggingface"
export HF_HUB_CACHE="/home/igutierrez134/.cache/huggingface"
export TOKENIZERS_PARALLELISM=false

echo "Qwen3-8B SF Spanish generation started on $(hostname)"
echo "Date: $(date)"
echo "SLURM_JOB_ID=${SLURM_JOB_ID:-}"
echo "SLURM_ARRAY_TASK_ID=${SLURM_ARRAY_TASK_ID:-}"
echo "CONFIG=${CONFIG}"
echo "CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES:-}"
nvidia-smi || true

python scripts/run_generation_from_config.py --config "$CONFIG"

echo "Qwen3-8B SF Spanish generation finished at $(date)"
