#!/usr/bin/env python
"""Patch the already-processed `query`/`justification` fields in place to
dash-bullet each composite line, matching prompts.format_question()'s and
prepare_sns1064.py's build_justification()'s current formatting.

query labels: "Tema: .../Subtema: .../Pregunta: .../Foco: ..." (Spanish),
"Gaia: .../Azpigaia: .../Galdera: .../Foku: ..." (Basque).
justification labels: "Evidencia procedente de la investigación: .../
Consideraciones adicionales: ..." (Spanish), "Ikerketatik datorren
ebidentzia: .../Gogoeta gehigarriak: ..." (Basque).

Spanish (guiasalud_casimedicos) is generated by prepare_sns1064.py +
build_guiasalud_casimedicos.py directly from the now-bulleted
format_question()/build_justification(), so both its fields are already
bulleted at the source -- this script is therefore a no-op there (kept
in TARGET_FILES anyway so a future re-run stays correct if that ever
changes). Basque (guiasalud_casimedicos_eu) is built from
scripts/translate_to_basque.py's machine-translated output, which was
translated before this formatting change existed and is not being
re-translated for a pure formatting fix -- this script's transform is
the text-level equivalent of what re-translating would produce for the
label lines specifically, without the MT cost/risk.

CasiMedicos-Exp records' query field (the bare exam question, no Tema/
Pregunta structure at all) and its justification (the doctors' free-text
explanation, no Evidencia/Consideraciones structure) are left untouched:
the label patterns below only ever match GuiaSalud-style composite lines,
so CasiMedicos-Exp text is a guaranteed no-op, not something this script
has to special-case.

Usage:
    python scripts/add_bullets_to_query_field.py --dry-run
    python scripts/add_bullets_to_query_field.py
"""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

TARGET_FILES = [
    "data/processed/guiasalud_casimedicos/train.jsonl",
    "data/processed/guiasalud_casimedicos/dev.jsonl",
    "data/processed/guiasalud_casimedicos/test.jsonl",
    "data/processed/guiasalud_casimedicos_eu/train.jsonl",
    "data/processed/guiasalud_casimedicos_eu/dev.jsonl",
    "data/processed/guiasalud_casimedicos_eu/test.jsonl",
]

# Matches a GuiaSalud composite line at the start of a line (or start of
# string). MULTILINE so ^ matches after each \n, not just at the string
# start. Covers both query's four labels and justification's two labels, in
# both languages, in one pattern, since a bare string-prefix match cannot
# accidentally cross between the two fields (they are patched independently
# below, each only ever sees its own field's text).
_LABEL_LINE_PATTERN = re.compile(
    r"^(Tema|Subtema|Pregunta|Foco|Gaia|Azpigaia|Galdera|Foku"
    r"|Evidencia procedente de la investigación|Consideraciones adicionales"
    r"|Ikerketatik datorren ebidentzia|Gogoeta gehigarriak): ",
    re.MULTILINE,
)


def add_bullets(text: str) -> str:
    return _LABEL_LINE_PATTERN.sub(r"- \1: ", text)


def process_file(path: Path, *, dry_run: bool) -> tuple[int, int]:
    if not path.exists():
        return 0, 0
    lines = path.read_text(encoding="utf-8").splitlines()
    changed = 0
    out_lines = []
    for line in lines:
        if not line.strip():
            out_lines.append(line)
            continue
        record = json.loads(line)
        record_changed = False
        for field in ("query", "justification"):
            value = record.get(field)
            if value:
                new_value = add_bullets(value)
                if new_value != value:
                    record[field] = new_value
                    record_changed = True
        if record_changed:
            changed += 1
        out_lines.append(json.dumps(record, ensure_ascii=False))
    if changed and not dry_run:
        path.write_text("\n".join(out_lines) + "\n", encoding="utf-8")
    return len(lines), changed


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    total_records = 0
    total_changed = 0
    for rel_path in TARGET_FILES:
        path = ROOT / rel_path
        n, changed = process_file(path, dry_run=args.dry_run)
        total_records += n
        total_changed += changed
        status = "would change" if args.dry_run else "changed"
        print(f"{rel_path}: {n} records, {changed} {status}")

    print(f"\nTotal: {total_records} records scanned, {total_changed} records "
          f"{'would have' if args.dry_run else 'had'} query/justification fields bulleted.")
    if args.dry_run:
        print("Dry run: no files written.")


if __name__ == "__main__":
    main()
